[build]
  command = "corepack enable && corepack prepare yarn@4.9.2 --activate && yarn install --frozen-lockfile && yarn workspace @facturacion/web build"
  publish = "apps/web/.next"

[functions]
  directory = "apps/web/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "https://api.facturacion-autonomos-monorepo.netlify.app/:splat"
  status = 200

[headers]
  [[headers]]
    for = "/*"
    [headers.values]
      Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';"
      X-Frame-Options = "DENY"