[build]
  # Build command optimizado para monorepo con SWC
  command = "cd apps/web && npm install --legacy-peer-deps && npm run build:netlify"
  
  # El plugin de Netlify maneja el directorio de publicación automáticamente
  publish = "apps/web/.next"
  
  # Base directory para rutas relativas
  base = "."

# Netlify Next.js plugin - maneja la compilación automáticamente
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Variables de entorno para el build
[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  # Forzar uso de SWC precompilado en entorno Linux
  SWC_BINARY_TARGET = "x86_64-unknown-linux-gnu"
  # Evitar problemas de compilación nativa
  NETLIFY_USE_YARN = "false"
  NPM_FLAGS = "--legacy-peer-deps"

# Production environment variables
[context.production.environment]
  NEXT_PUBLIC_APP_URL = "https://facturacion-autonomos.netlify.app"
  NEXT_PUBLIC_API_BASE_URL = "https://facturacion-autonomos.netlify.app/api"

# Branch deploys environment
[context.branch-deploy.environment]  
  NEXT_PUBLIC_APP_URL = "https://deploy-preview-{REVIEW_ID}--facturacion-autonomos.netlify.app"
  NEXT_PUBLIC_API_BASE_URL = "https://deploy-preview-{REVIEW_ID}--facturacion-autonomos.netlify.app/api"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
