[build]
  command = "corepack enable && corepack prepare yarn@4.9.2 --activate && yarn install --frozen-lockfile && yarn workspace @facturacion/web build"
  publish = "apps/web/.next"
<<<<<<< HEAD
  base = "."
=======

[functions]
  directory = "apps/web/functions"
>>>>>>> origin/develop

[[plugins]]
  package = "@netlify/plugin-nextjs"

<<<<<<< HEAD
[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "20"
  COREPACK_ENABLE_STRICT = "0"
  YARN_ENABLE_IMMUTABLE_INSTALLS = "true"

[context.production.environment]
  NEXT_PUBLIC_APP_URL = "https://facturacion-autonomos.netlify.app"
  NEXT_PUBLIC_API_BASE_URL = "https://facturacion-autonomos.netlify.app/api"

[context.branch-deploy.environment]  
  NEXT_PUBLIC_APP_URL = "https://deploy-preview-{REVIEW_ID}--facturacion-autonomos.netlify.app"
  NEXT_PUBLIC_API_BASE_URL = "https://deploy-preview-{REVIEW_ID}--facturacion-autonomos.netlify.app/api"
=======
[[redirects]]
  from = "/api/*"
  to = "https://api.facturacion-autonomos-monorepo.netlify.app/:splat"
  status = 200
>>>>>>> origin/develop

[[headers]]
  for = "/*"
  [headers.values]
<<<<<<< HEAD
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
=======
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';"
    X-Frame-Options = "DENY"
>>>>>>> origin/develop
