[build]
  command = "corepack enable && corepack prepare yarn@4.9.2 --activate && yarn install --immutable && yarn workspace @facturacion/web build"
  publish = "apps/web/.next"
  base = "."

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "20"
  COREPACK_ENABLE_STRICT = "0"
  YARN_ENABLE_IMMUTABLE_INSTALLS = "true"

[context.production.environment]
  NEXT_PUBLIC_APP_URL = "https://facturacion-autonomos-monorepo.netlify.app"
  NEXT_PUBLIC_API_BASE_URL = "https://facturacion-autonomos-monorepo.netlify.app/api"

[context.branch-deploy.environment]  
  NEXT_PUBLIC_APP_URL = "https://deploy-preview-${REVIEW_ID}--facturacion-autonomos-monorepo.netlify.app"
  NEXT_PUBLIC_API_BASE_URL = "https://deploy-preview-${REVIEW_ID}--facturacion-autonomos-monorepo.netlify.app/api"

[functions]
  directory = "apps/web/functions"

[dev]
  command = "cd apps/web && yarn dev"
  port = 8888

[dev.functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "https://api.facturacion-autonomos-monorepo.netlify.app/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self'; connect-src 'self' https:; frame-ancestors 'none';"
    
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Frame-Options = "DENY"
