openapi: 3.0.3
info:
  title: API Facturación Autónomos
  version: 1.0.0
  description: API para OCR de facturas, reporting fiscal y resúmenes históricos.
servers:
  - url: http://localhost:3000/api
paths:
  /ocr/process:
    post:
      summary: Procesar factura con OCR
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Resultado del procesamiento OCR
        '400':
          description: Error de validación
        '500':
          description: Error interno
  /tax-reporting/structure:
    get:
      summary: Obtener estructura de reporting fiscal
      parameters:
        - in: query
          name: userId
          schema:
            type: string
          required: true
        - in: query
          name: quarter
          schema:
            type: string
          required: false
        - in: query
          name: year
          schema:
            type: integer
          required: false
      responses:
        '200':
          description: Estructura fiscal agregada
        '401':
          description: Falta userId
        '500':
          description: Error interno
  /user/fiscal-summary/historical:
    get:
      summary: Obtener resumen fiscal histórico
      parameters:
        - in: query
          name: userId
          schema:
            type: string
          required: true
        - in: query
          name: quarters
          schema:
            type: integer
          required: false
      responses:
        '200':
          description: Datos históricos fiscales
        '401':
          description: Falta userId
        '404':
          description: No hay datos
        '500':
          description: Error interno
