"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.metadata = void 0;
exports.default = RootLayout;
const google_1 = require("next/font/google");
require("./globals.css");
const client_layout_1 = require("./client-layout");
const inter = (0, google_1.Inter)({ subsets: ["latin"] });
exports.metadata = {
    title: "TributariApp",
    description: "Generated by create next app",
    generator: 'v0.dev'
};
function RootLayout({ children, }) {
    return <client_layout_1.default>{children}</client_layout_1.default>;
}
