openapi: 3.0.3
info:
  title: Auth Service API
  description: |
    Servicio de autenticación y autorización para el sistema de facturación

    ## Características principales:
    - Autenticación JWT con refresh tokens
    - Registro de usuarios con validación
    - Gestión de sesiones seguras
    - Integración con 2FA (futuro)
    - Rate limiting y protección DDoS

  version: 1.0.0
  contact:
    name: Equipo de Desarrollo
    email: dev@facturacion-autonomos.com

servers:
  - url: http://localhost:3003/api
    description: Auth Service - Desarrollo
  - url: https://auth.facturacion-autonomos.com/api
    description: Auth Service - Producción

security:
  - bearerAuth: []

paths:
  /auth/register:
    post:
      summary: 📝 Registrar nuevo usuario
      description: Crea una nueva cuenta de usuario con validación completa
      tags: [🔐 Autenticación]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - name
              properties:
                email:
                  type: string
                  format: email
                  description: Email único del usuario
                  example: 'usuario@ejemplo.com'
                password:
                  type: string
                  minLength: 8
                  description: Contraseña segura (mínimo 8 caracteres)
                  example: 'password123'
                name:
                  type: string
                  minLength: 2
                  description: Nombre completo del usuario
                  example: 'Juan Pérez'
                phone:
                  type: string
                  description: Teléfono opcional
                  example: '+34612345678'
      responses:
        201:
          description: ✅ Usuario registrado exitosamente
          headers:
            Set-Cookie:
              description: Cookie de sesión segura
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      user:
                        $ref: '#/components/schemas/User'
                      tokens:
                        $ref: '#/components/schemas/AuthTokens'
                  message:
                    type: string
                    example: 'Usuario registrado exitosamente'
        400:
          $ref: '#/components/responses/ValidationError'
        409:
          description: ⚠️ Usuario ya existe
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: 'USER_EXISTS'
                      message:
                        type: string
                        example: 'Ya existe un usuario con este email'

  /auth/login:
    post:
      summary: 🔑 Iniciar sesión
      description: Autentica al usuario y devuelve tokens de acceso
      tags: [🔐 Autenticación]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: 'usuario@ejemplo.com'
                password:
                  type: string
                  example: 'password123'
      responses:
        200:
          description: ✅ Login exitoso
          headers:
            Set-Cookie:
              description: Cookie de sesión con refresh token
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      user:
                        $ref: '#/components/schemas/User'
                      tokens:
                        $ref: '#/components/schemas/AuthTokens'
                  message:
                    type: string
                    example: 'Login exitoso'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        429:
          description: 🚫 Demasiados intentos
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: 'TOO_MANY_REQUESTS'
                      message:
                        type: string
                        example: 'Demasiados intentos de login. Intente más tarde'

  /auth/refresh:
    post:
      summary: 🔄 Refrescar token
      description: Obtiene un nuevo token de acceso usando el refresh token
      tags: [🔐 Autenticación]
      security:
        - bearerAuth: []
      responses:
        200:
          description: ✅ Token refrescado
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      tokens:
                        $ref: '#/components/schemas/AuthTokens'
        401:
          $ref: '#/components/responses/UnauthorizedError'

  /auth/logout:
    post:
      summary: 🚪 Cerrar sesión
      description: Invalida la sesión actual del usuario
      tags: [🔐 Autenticación]
      security:
        - bearerAuth: []
      responses:
        200:
          description: ✅ Sesión cerrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Sesión cerrada exitosamente'
        401:
          $ref: '#/components/responses/UnauthorizedError'

  /auth/me:
    get:
      summary: 👤 Información del usuario actual
      description: Obtiene la información del usuario autenticado
      tags: [🔐 Autenticación]
      security:
        - bearerAuth: []
      responses:
        200:
          description: ✅ Información del usuario
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/User'
        401:
          $ref: '#/components/responses/UnauthorizedError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: '123e4567-e89b-12d3-a456-426614174000'
        email:
          type: string
          format: email
          example: 'usuario@ejemplo.com'
        name:
          type: string
          example: 'Juan Pérez'
        phone:
          type: string
          example: '+34612345678'
        role:
          type: string
          enum: [user, admin]
          example: 'user'
        isActive:
          type: boolean
          example: true
        createdAt:
          type: string
          format: date-time
          example: '2024-01-15T10:30:00Z'
        updatedAt:
          type: string
          format: date-time
          example: '2024-01-15T10:30:00Z'

    AuthTokens:
      type: object
      properties:
        accessToken:
          type: string
          description: Token JWT para acceso a recursos
          example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'
        refreshToken:
          type: string
          description: Token para refrescar el access token
          example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'
        expiresIn:
          type: integer
          description: Segundos hasta expiración del access token
          example: 3600
        tokenType:
          type: string
          example: 'Bearer'

  responses:
    UnauthorizedError:
      description: No autorizado - Credenciales inválidas
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              error:
                type: object
                properties:
                  code:
                    type: string
                    example: 'INVALID_CREDENTIALS'
                  message:
                    type: string
                    example: 'Email o contraseña incorrectos'

    ValidationError:
      description: Datos de entrada inválidos
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              error:
                type: object
                properties:
                  code:
                    type: string
                    example: 'VALIDATION_ERROR'
                  message:
                    type: string
                    example: 'Los datos proporcionados no son válidos'
                  details:
                    type: object
                    additionalProperties:
                      type: string
