apiVersion: v1
kind: Service
metadata:
  name: api-tax-calculator-service
  namespace: ${KUBE_NAMESPACE}
  labels:
    app: api-tax-calculator
    environment: ${ENVIRONMENT}
spec:
  selector:
    app: api-tax-calculator
  ports:
    - port: 3001
      targetPort: 3001
      name: http
    - port: 9090
      targetPort: 9090
      name: metrics
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-tax-calculator
  namespace: ${KUBE_NAMESPACE}
  labels:
    app: api-tax-calculator
    environment: ${ENVIRONMENT}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-tax-calculator
  template:
    metadata:
      labels:
        app: api-tax-calculator
        environment: ${ENVIRONMENT}
    spec:
      containers:
        - name: api-tax-calculator
          image: ${API_TAX_CALCULATOR_IMAGE}:${CI_COMMIT_SHA}
          ports:
            - containerPort: 3001
            - containerPort: 9090
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: facturacion-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: facturacion-config
                  key: API_TAX_CALCULATOR_PORT
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: facturacion-config
                  key: API_TAX_CALCULATOR_HOST
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: facturacion-secret
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: facturacion-secret
                  key: JWT_SECRET
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: facturacion-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: facturacion-config
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: facturacion-secret
                  key: REDIS_PASSWORD
                  optional: true
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: facturacion-config
                  key: LOG_LEVEL
            - name: LOG_FORMAT
              valueFrom:
                configMapKeyRef:
                  name: facturacion-config
                  key: LOG_FORMAT
            - name: CORS_ORIGIN
              valueFrom:
                secretKeyRef:
                  name: facturacion-secret
                  key: CORS_ORIGIN
            - name: RATE_LIMIT_WINDOW
              valueFrom:
                configMapKeyRef:
                  name: facturacion-config
                  key: RATE_LIMIT_WINDOW
            - name: RATE_LIMIT_MAX
              valueFrom:
                configMapKeyRef:
                  name: facturacion-config
                  key: RATE_LIMIT_MAX
            - name: WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: facturacion-secret
                  key: WEBHOOK_SECRET
            - name: ENABLE_METRICS
              valueFrom:
                configMapKeyRef:
                  name: facturacion-config
                  key: ENABLE_METRICS
            - name: METRICS_PORT
              valueFrom:
                configMapKeyRef:
                  name: facturacion-config
                  key: METRICS_PORT
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: facturacion-secret
                  key: SENTRY_DSN
                  optional: true
            - name: API_FACTURAS_URL
              valueFrom:
                configMapKeyRef:
                  name: facturacion-config
                  key: API_FACTURAS_URL
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 12
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: api-tax-calculator-monitor
  namespace: ${KUBE_NAMESPACE}
  labels:
    app: api-tax-calculator
    environment: ${ENVIRONMENT}
spec:
  selector:
    matchLabels:
      app: api-tax-calculator
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
