apiVersion: v1
kind: Service
metadata:
  name: api-facturas-service
  namespace: ${KUBE_NAMESPACE}
  labels:
    app: api-facturas
    environment: ${ENVIRONMENT}
spec:
  selector:
    app: api-facturas
  ports:
    - port: 3000
      targetPort: 3000
      name: http
    - port: 9090
      targetPort: 9090
      name: metrics
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-facturas
  namespace: ${KUBE_NAMESPACE}
  labels:
    app: api-facturas
    environment: ${ENVIRONMENT}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-facturas
  template:
    metadata:
      labels:
        app: api-facturas
        environment: ${ENVIRONMENT}
    spec:
      containers:
        - name: api-facturas
          image: ${API_FACTURAS_IMAGE}:${CI_COMMIT_SHA}
          ports:
            - containerPort: 3000
            - containerPort: 9090
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: facturacion-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: facturacion-config
                  key: API_FACTURAS_PORT
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: facturacion-config
                  key: API_FACTURAS_HOST
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: facturacion-secret
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: facturacion-secret
                  key: JWT_SECRET
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: facturacion-secret
                  key: JWT_REFRESH_SECRET
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: facturacion-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: facturacion-config
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: facturacion-secret
                  key: REDIS_PASSWORD
                  optional: true
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: facturacion-config
                  key: LOG_LEVEL
            - name: LOG_FORMAT
              valueFrom:
                configMapKeyRef:
                  name: facturacion-config
                  key: LOG_FORMAT
            - name: CORS_ORIGIN
              valueFrom:
                secretKeyRef:
                  name: facturacion-secret
                  key: CORS_ORIGIN
            - name: RATE_LIMIT_WINDOW
              valueFrom:
                configMapKeyRef:
                  name: facturacion-config
                  key: RATE_LIMIT_WINDOW
            - name: RATE_LIMIT_MAX
              valueFrom:
                configMapKeyRef:
                  name: facturacion-config
                  key: RATE_LIMIT_MAX
            - name: AEAT_API_URL
              valueFrom:
                configMapKeyRef:
                  name: facturacion-config
                  key: AEAT_API_URL
            - name: AEAT_CERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: facturacion-secret
                  key: AEAT_CERTIFICATE
            - name: AEAT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: facturacion-secret
                  key: AEAT_PRIVATE_KEY
            - name: ENABLE_METRICS
              valueFrom:
                configMapKeyRef:
                  name: facturacion-config
                  key: ENABLE_METRICS
            - name: METRICS_PORT
              valueFrom:
                configMapKeyRef:
                  name: facturacion-config
                  key: METRICS_PORT
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: facturacion-secret
                  key: SENTRY_DSN
                  optional: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 12
      initContainers:
        - name: prisma-migrate
          image: ${API_FACTURAS_IMAGE}:${CI_COMMIT_SHA}
          command:
            - sh
            - -c
            - |
              echo "Running Prisma migrations..."
              npx prisma migrate deploy
              echo "Prisma migrations completed"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: facturacion-secret
                  key: DATABASE_URL
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: api-facturas-monitor
  namespace: ${KUBE_NAMESPACE}
  labels:
    app: api-facturas
    environment: ${ENVIRONMENT}
spec:
  selector:
    matchLabels:
      app: api-facturas
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
