apiVersion: v1
kind: ConfigMap
metadata:
  name: facturacion-config
  namespace: ${KUBE_NAMESPACE}
  labels:
    app: facturacion
    environment: ${ENVIRONMENT}
data:
  # Base de datos
  POSTGRES_HOST: postgres-service
  POSTGRES_PORT: "5432"
  POSTGRES_DB: facturacion_${ENVIRONMENT}
  POSTGRES_USER: postgres
  
  # Redis
  REDIS_HOST: redis-service
  REDIS_PORT: "6379"
  
  # API Facturas
  API_FACTURAS_PORT: "3000"
  API_FACTURAS_HOST: "0.0.0.0"
  
  # API Tax Calculator
  API_TAX_CALCULATOR_PORT: "3001"
  API_TAX_CALCULATOR_HOST: "0.0.0.0"
  
  # Web
  WEB_PORT: "3002"
  WEB_HOST: "0.0.0.0"
  
  # Entorno
  NODE_ENV: ${ENVIRONMENT}
  
  # APIs externas
  AEAT_API_URL: "https://www1.agenciatributaria.gob.es/wlpl/SSII-FACT/ws/fe/SiiFactFEV1SOAP"
  
  # Configuración de logs
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  
  # Configuración de seguridad
  CORS_ORIGIN: "*"
  RATE_LIMIT_WINDOW: "900000"  # 15 minutos
  RATE_LIMIT_MAX: "100"
  
  # Configuración de Prisma
  PRISMA_CLI_QUERY_ENGINE_TYPE: "binary"
  
  # URLs de servicios internos
  API_FACTURAS_URL: "http://api-facturas-service:3000"
  API_TAX_CALCULATOR_URL: "http://api-tax-calculator-service:3001"
  
  # Configuración de health checks
  HEALTH_CHECK_INTERVAL: "30000"  # 30 segundos
  HEALTH_CHECK_TIMEOUT: "5000"    # 5 segundos
  
  # Configuración de monitoreo
  ENABLE_METRICS: "true"
  METRICS_PORT: "9090"
  
  # Configuración de cache
  CACHE_TTL: "300"  # 5 minutos
  CACHE_PREFIX: "facturacion_${ENVIRONMENT}"
