apiVersion: v1
kind: Secret
metadata:
  name: facturacion-secret
  namespace: ${KUBE_NAMESPACE}
  labels:
    app: facturacion
    environment: ${ENVIRONMENT}
type: Opaque
data:
  # Base de datos (valores base64)
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_B64}
  DATABASE_URL: ${DATABASE_URL_B64}
  
  # Secrets JWT
  JWT_SECRET: ${JWT_SECRET_B64}
  JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET_B64}
  
  # API Keys
  AEAT_CERTIFICATE: ${AEAT_CERTIFICATE_B64}
  AEAT_PRIVATE_KEY: ${AEAT_PRIVATE_KEY_B64}
  
  # Secrets de terceros
  SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL_B64}
  
  # Encryption keys
  ENCRYPTION_KEY: ${ENCRYPTION_KEY_B64}
  
  # Session secret
  SESSION_SECRET: ${SESSION_SECRET_B64}
  
  # SMTP configuración
  SMTP_HOST: ${SMTP_HOST_B64}
  SMTP_PORT: ${SMTP_PORT_B64}
  # Redis password (opcional)
  REDIS_PASSWORD: ${REDIS_PASSWORD_B64}
  
  # Monitoring
  SENTRY_DSN: ${SENTRY_DSN_B64}
  
  # External APIs
  EXTERNAL_API_KEY: ${EXTERNAL_API_KEY_B64}
  
stringData:
  # Datos que no necesitan ser base64
  CORS_ORIGIN: "*"
  ALLOWED_ORIGINS: "https://facturacion.example.com,https://facturacion-staging.example.com"
