name: 🤖 Dependabot Auto-Merge

on:
  pull_request:
    branches: [main, develop]

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot-auto-merge:
    name: 🤖 Auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - uses: actions/checkout@v4

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Auto-merge for Dependabot
        if: >
          steps.metadata.outputs.update-type == 'version-update:semver-patch' &&
          steps.metadata.outputs.dependency-type == 'direct'
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-approve for Dependabot
        if: >
          steps.metadata.outputs.update-type == 'version-update:semver-patch' &&
          steps.metadata.outputs.dependency-type == 'direct'
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR for manual review
        if: >
          steps.metadata.outputs.update-type != 'version-update:semver-patch' ||
          steps.metadata.outputs.dependency-type != 'direct'
        run: |
          gh pr comment "$PR_URL" --body "🤖 This PR requires manual review because it contains:
          - Update type: ${{ steps.metadata.outputs.update-type }}
          - Dependency type: ${{ steps.metadata.outputs.dependency-type }}
          - Dependency: ${{ steps.metadata.outputs.dependency-names }}"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}