name: Test

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Enable Corepack
        run: corepack enable

      - name: Install Yarn 4.x
        run: corepack prepare yarn@4.9.2 --activate

      - name: Verify Yarn version
        run: yarn --version

      - name: Install dependencies
        run: yarn install --immutable-cache --check-cache

      - name: Run tests
        run: yarn test --passWithNoTests